/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "stdio.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0  (GUI_ID_USER + 0x00)
#define ID_BUTTON_0  (GUI_ID_USER + 0x01)
#define ID_BUTTON_1  (GUI_ID_USER + 0x02)
#define ID_BUTTON_2  (GUI_ID_USER + 0x03)
#define ID_BUTTON_3  (GUI_ID_USER + 0x04)
#define ID_BUTTON_4  (GUI_ID_USER + 0x05)
#define ID_BUTTON_5  (GUI_ID_USER + 0x06)
#define ID_BUTTON_6  (GUI_ID_USER + 0x07)
#define ID_BUTTON_7  (GUI_ID_USER + 0x08)
#define ID_BUTTON_8  (GUI_ID_USER + 0x09)
#define ID_BUTTON_9  (GUI_ID_USER + 0x0A)
#define ID_BUTTON_10  (GUI_ID_USER + 0x0B)
#define ID_BUTTON_11  (GUI_ID_USER + 0x0C)
#define ID_BUTTON_12  (GUI_ID_USER + 0x0D)
#define ID_BUTTON_13  (GUI_ID_USER + 0x0E)
#define ID_BUTTON_14  (GUI_ID_USER + 0x0F)
#define ID_BUTTON_15  (GUI_ID_USER + 0x10)
#define ID_BUTTON_16  (GUI_ID_USER + 0x11)
#define ID_BUTTON_17  (GUI_ID_USER + 0x12)
#define ID_EDIT_0  (GUI_ID_USER + 0x13)
#define ID_TEXT_0  (GUI_ID_USER + 0x14)


// USER START (Optionally insert additional defines)
typedef enum{
	OPERATION_NONE = 0,
	OPERATION_ADD,
	OPERATION_SUB,
	OPERATION_MUL,
	OPERATION_DIV,
}OPERATION_Typedef;
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
extern GUI_CONST_STORAGE GUI_FONT GUI_FontConsolas60;
// Display Text variable
static char DisplayText[50];
static int DisplayTextCnt = 0;
static int DotPressed = 0;

// Calculate part variable
static int CurrentResultCalculated = 0;
static OPERATION_Typedef CalculationOperation = OPERATION_NONE;
static double OperationNumber1;
static double OperationNumber2;
static double CalculateResult;
static U32 CalculateError;
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, -1, 480, 272, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "0", ID_BUTTON_0, 30, 70, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "1", ID_BUTTON_1, 110, 70, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "2", ID_BUTTON_2, 190, 70, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "3", ID_BUTTON_3, 30, 110, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "4", ID_BUTTON_4, 110, 110, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "5", ID_BUTTON_5, 190, 110, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "6", ID_BUTTON_6, 30, 150, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "7", ID_BUTTON_7, 110, 150, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "8", ID_BUTTON_8, 190, 150, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "9", ID_BUTTON_9, 30, 190, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, ".", ID_BUTTON_10, 110, 190, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "00", ID_BUTTON_11, 190, 190, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "+", ID_BUTTON_12, 270, 70, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "-", ID_BUTTON_13, 270, 110, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "*", ID_BUTTON_14, 270, 150, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "/", ID_BUTTON_15, 270, 190, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Clear", ID_BUTTON_16, 350, 70, 80, 80, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "=", ID_BUTTON_17, 350, 150, 80, 80, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_0, 30, 10, 400, 55, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 105, 232, 291, 37, 0, 0x64, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)


static void AppendCharToDisplayText(WM_MESSAGE * pMsg, WM_HWIN hItem, char* AppendChar){
	if (CurrentResultCalculated == 0){	
		if (DotPressed == 1 && AppendChar[0] == '.')
			return;
			
		if (DisplayTextCnt == 0){
			if (AppendChar[0] == '.') { // .
				sprintf(DisplayText,"0.");
				DisplayTextCnt++;
			}
			else if (AppendChar[0] == '0'){ // 00
				sprintf(DisplayText, "0");
			}
			else {
				sprintf(DisplayText, "%s", AppendChar);
				DisplayTextCnt++;
			}
		}
		else{
			sprintf(DisplayText, "%s%s", DisplayText, AppendChar);
			if (AppendChar[1] != 0)
				DisplayTextCnt++;
			DisplayTextCnt++;
		}					
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
		EDIT_SetText(hItem, DisplayText);
	}	
}

static void ClearDisplayText(WM_MESSAGE * pMsg, WM_HWIN hItem){
	
	sprintf(DisplayText, "0");
	DisplayTextCnt = 0;
	DotPressed = 0;
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
	EDIT_SetMaxLen(hItem,100);
	EDIT_SetTextColor(hItem, EDIT_CI_ENABELD, GUI_MAKE_COLOR(0x00000000));
	EDIT_SetText(hItem, DisplayText);
}

void ClearCalculation(void){
	CurrentResultCalculated = 0;
	OperationNumber1 = 0;
	OperationNumber2 = 0;
	CalculateResult = 0;
	CalculationOperation = OPERATION_NONE;
}

double ConvertStringToDouble(char* ConvertString){
	if (ConvertString == NULL)
		return 0;
	int i = 0;
	int IntegerPart = 0;
	double DigitPart = 0;
	
	while(ConvertString[i] != 0){
			if (DigitPart != 0)
				DigitPart /= 10; 
			if (ConvertString[i] == '.')
				DigitPart = 1;
			if (ConvertString[i] >= '0' && ConvertString[i] <= '9')
				IntegerPart = IntegerPart*10 + ConvertString[i] - '0'; 
			i++;
	}
	if (DigitPart == 0)
		DigitPart = 1;
	return (double)(IntegerPart * DigitPart);
}

U32 CalculateProcess(OPERATION_Typedef Operation, double OperationNumber1, double OperationNumber2, double* CalculateResult){
		if (Operation == OPERATION_NONE){
			*CalculateResult = 0;
			return 0;
		}
		if (Operation == OPERATION_DIV && OperationNumber1 == 0 && OperationNumber2 == 0){
			*CalculateResult = 0;
			return 0;
		}
		if (Operation == OPERATION_DIV && OperationNumber2 == 0)
			return 1;
		
		if (Operation == OPERATION_ADD){
			*CalculateResult = OperationNumber1 + OperationNumber2;
			return 0;
		}
		
		if (Operation == OPERATION_SUB){
			*CalculateResult = OperationNumber1 - OperationNumber2;
			return 0;
		}		
		
		if (Operation == OPERATION_MUL){
			*CalculateResult = OperationNumber1 * OperationNumber2;
			return 0;
		}		
		
		if (Operation == OPERATION_DIV){
			*CalculateResult = OperationNumber1 / OperationNumber2;
			return 0;
		}		
		
		return 1;
}

void DispalyCalculateResult(WM_MESSAGE * pMsg, WM_HWIN hItem, U32 Error, double Result){
	// display text
	char DisplayTextBuffer[50];
	char dot;
	int i;
	
	if (Error != 0){
		sprintf(DisplayTextBuffer, "Error");
	}
	else{
		// integer
		if (Result == (long long int)Result){
			sprintf(DisplayTextBuffer,"%.0lf", Result);
		}
		else{// floatint  point
			sprintf(DisplayTextBuffer,"%.10lf", Result);
			dot = 0;
			// check there are a dot in 10 digits
			for(i = 0; i < 10;i++){
				if (DisplayTextBuffer[i]=='.'){
					dot = 1; 
					break;
				}
			}
			// have dot
			if (dot == 1){
				if (DisplayTextBuffer[10]>='5' && DisplayTextBuffer[10]!='.'){
					DisplayTextBuffer[9] = (DisplayTextBuffer[9] == '9') ? '9' :
																 (DisplayTextBuffer[9] == '.') ? '.' :
								                  ++DisplayTextBuffer[9];				
				}
				i = 9; // remove 0
				while(DisplayTextBuffer[i] == '0'){
					if (DisplayTextBuffer[10]!='0' && DisplayTextBuffer[9]=='0'){
						break;
					}
					if (i == 0){
						break;	
					}
					DisplayTextBuffer[i] = '\0';	
					i--;
				}
				
				if (DisplayTextBuffer[i] == '.'){
					DisplayTextBuffer[i] = '\0';
				}
			}		
			DisplayTextBuffer[10]='\0';

		}
		//sprintf(text,"%.8lf", result);
	}
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
	EDIT_SetTextColor(hItem, EDIT_CI_ENABELD, GUI_MAKE_COLOR(0x0000FF));
	EDIT_SetMaxLen(hItem,10);
	EDIT_SetText(hItem, DisplayTextBuffer);
	
}

// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
	
	
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of '0'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of '1'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of '2'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of '3'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
    BUTTON_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of '4'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
    BUTTON_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of '5'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
    BUTTON_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of '6'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);
    BUTTON_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of '7'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7);
    BUTTON_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of '8'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8);
    BUTTON_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of '9'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_9);
    BUTTON_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of '.'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_10);
    BUTTON_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of '00'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_11);
    BUTTON_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of '+'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_12);
    BUTTON_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of '-'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_13);
    BUTTON_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of '*'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_14);
    BUTTON_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of 'Clear'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_16);
    BUTTON_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    EDIT_SetText(hItem, "0");
    EDIT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
    EDIT_SetFont(hItem, &GUI_FontConsolas60);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, GUI_FONT_24_1);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FF8000));
    TEXT_SetText(hItem, "NTUST B10602225");
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by '0'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				AppendCharToDisplayText(pMsg, hItem, "0");
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by '1'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				AppendCharToDisplayText(pMsg, hItem, "1");
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by '2'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				AppendCharToDisplayText(pMsg, hItem, "2");
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by '3'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				AppendCharToDisplayText(pMsg, hItem, "3");
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_4: // Notifications sent by '4'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				AppendCharToDisplayText(pMsg, hItem, "4");
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_5: // Notifications sent by '5'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				AppendCharToDisplayText(pMsg, hItem, "5");	
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_6: // Notifications sent by '6'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				AppendCharToDisplayText(pMsg, hItem, "6");
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_7: // Notifications sent by '7'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				AppendCharToDisplayText(pMsg, hItem, "7");
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_8: // Notifications sent by '8'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				AppendCharToDisplayText(pMsg, hItem, "8");
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_9: // Notifications sent by '9'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				AppendCharToDisplayText(pMsg, hItem, "9");
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_10: // Notifications sent by '.'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				AppendCharToDisplayText(pMsg, hItem, ".");
				DotPressed = 1;
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_11: // Notifications sent by '00'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				AppendCharToDisplayText(pMsg, hItem, "00");
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_12: // Notifications sent by '+'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				if (CurrentResultCalculated == 0){
					OperationNumber1 = ConvertStringToDouble(DisplayText);
					CalculationOperation = OPERATION_ADD;
					sprintf(DisplayText, "0");
					DisplayTextCnt = 0;
					DotPressed = 0;
				}
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_13: // Notifications sent by '-'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				if (CurrentResultCalculated == 0){
					OperationNumber1 = ConvertStringToDouble(DisplayText);
					CalculationOperation = OPERATION_SUB;
					sprintf(DisplayText, "0");
					DisplayTextCnt = 0;
					DotPressed = 0;
				}				
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_14: // Notifications sent by '*'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				if (CurrentResultCalculated == 0){
					OperationNumber1 = ConvertStringToDouble(DisplayText);
					CalculationOperation = OPERATION_MUL;
					sprintf(DisplayText, "0");
					DisplayTextCnt = 0;
					DotPressed = 0;
				}
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_15: // Notifications sent by '/'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				if (CurrentResultCalculated == 0){
					OperationNumber1 = ConvertStringToDouble(DisplayText);
					CalculationOperation = OPERATION_DIV;
					sprintf(DisplayText, "0");
					DisplayTextCnt = 0;
					DotPressed = 0;
				}
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_16: // Notifications sent by 'Clear'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				ClearDisplayText(pMsg, hItem);
				ClearCalculation();

        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_17: // Notifications sent by '='
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				OperationNumber2 = ConvertStringToDouble(DisplayText);
				CalculateError = CalculateProcess(CalculationOperation, OperationNumber1, OperationNumber2, &CalculateResult);
				DispalyCalculateResult(pMsg, hItem, CalculateError, CalculateResult);
				CurrentResultCalculated = 1;
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_0: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindow(void);
WM_HWIN CreateWindow(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
